name: CI

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.2

      - name: Install PHP dependencies
        run: composer install --ignore-platform-reqs

      - name: Run PHP tests
        run: ./vendor/bin/phpunit php-tests

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install JS dependencies
        run: npm install

      - name: Run JS tests
        run: npm test

      - name: Run Gitleaks
        uses: gitleaks/gitleaks-action@v2
        continue-on-error: true
